clear
clc
% Extract the candidate controller gains.
  kp=0.3;
  ki=0.2;
    
  % Form the open-loop transfer function.
  olNum = [(kp+ki)*(1-exp(-1)) ...
           -kp*(1-exp(-1))];
  
  olDen = [1 ...
           -1-exp(-1) ...
           exp(-1) ...
           0 ...
           0];
  
  % Form the closed-loop transfer function.
  clNum=[(1-exp(-1))*(kp+ki) ...
         -(kp/(kp+ki))*(1-exp(-1))*(kp+ki)];
  clDen=[1 ...
         -(1+exp(-1)) ...
         exp(-1) ...
         (1-exp(-1))*(kp+ki) ...
	 -(kp/(kp+ki))*(1-exp(-1))*(kp+ki)];
 
  % Get stability measure.
  sPoles = roots(clDen);
  clStable = max(abs(sPoles));
      
  olTF = tf(olNum, olDen, 1.0);
  [a,b,c,d]=margin(olTF)